apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: gitops
spec:
  rbac:
    defaultPolicy: 'role:admin'
    policy: |
      g, cluster-admins, role:admin
    scopes: '[groups]'
  server: 
    route:
      enabled: true